# frozen_string_literal: true

default_platform(:android)

platform :android do
  desc "Runs all unit tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build debug APK"
  lane :build_debug do
    gradle(task: "assembleDebug")
  end

  desc "Build release APK"
  lane :build_release do
    gradle(task: "assembleRelease")
  end
end
