name: Build LSPosed Module

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java Development Kit (JDK)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 1: Compiles a clean, highly compressed Release APK
    - name: Compile Release APK using Gradle
      run: gradle assembleRelease

    # Step 2: Generates an on-the-fly signing key and signs the Release APK
    - name: Sign Release APK
      run: |
        keytool -genkey -v -keystore release.keystore -alias signAlias -keyalg RSA -keysize 2048 -validity 10000 -storepass mypassword -keypass mypassword -dname "CN=dhangofa, O=Github, C=US"
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA256 -keystore release.keystore -storepass mypassword app/build/outputs/apk/release/app-release-unsigned.apk signAlias
        mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/BatteryRemapper.apk

    # Step 3: Uploads the direct raw .apk without zip encapsulation
    - name: Upload APK Directly
      uses: actions/upload-artifact@v7
      with:
        path: app/build/outputs/apk/release/BatteryRemapper.apk
        archive: false # Tells GitHub to serve the raw .apk file directly
